version: '3.8'

services:
  jarvis-app:
    build: .
    container_name: jarvis_leitor_tela
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DISPLAY=host.docker.internal:0.0
    network_mode: "host"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
