import os
import subprocess
import tempfile
import shutil
from pathlib import Path

class Holodeck:
    """
    Process isolation system (Holodeck) for executing autogenerated code.
    Implements a virtual overlay to prevent root filesystem modification.
    """

    def __init__(self, root_sandbox_dir: str = "/tmp/holodeck_sandbox"):
        self.root_sandbox = Path(root_sandbox_dir)
        try:
            self.root_sandbox.mkdir(parents=True, exist_ok=True)
        except OSError:
            # Fallback for Windows environments
            self.root_sandbox = Path(tempfile.gettempdir()) / "holodeck_sandbox"
            self.root_sandbox.mkdir(parents=True, exist_ok=True)

    def create_overlay(self) -> Path:
        """Creates a unique session overlay directory."""
        session_id = os.urandom(8).hex()
        overlay_path = self.root_sandbox / session_id
        overlay_path.mkdir()
        return overlay_path

    def execute_isolated(self, code: str, timeout: int = 30):
        """Executes code within a temporary overlay with restricted environment."""
        overlay = self.create_overlay()
        script_path = overlay / "runtime_exec.py"

        try:
            with open(script_path, "w") as f:
                f.write(code)

            # Execution with environment scrubbing
            result = subprocess.run(
                ["python3", str(script_path)],
                cwd=str(overlay),
                capture_output=True,
                text=True,
                timeout=timeout,
                env={"PYTHONPATH": str(overlay), "HOME": str(overlay)}
            )

            return {
                "stdout": result.stdout,
                "stderr": result.stderr,
                "exit_code": result.returncode
            }
        except subprocess.TimeoutExpired:
            return {"error": "Execution timed out", "exit_code": 124}
        finally:
            shutil.rmtree(overlay)
